Library Management System/project/lms/urls.py
from django.urls import path
from.import views
app_name = "lms"

urlpatterns = [
    path("lms/dashboard/", views.dashboard,name="dashboard"),
    path("", views.home,name="home"),
    path("accounts/login/", views.login_user, name="login_user"),
    path("accounts/sigup/", views.signup_user, name = "signup_user"),
    path("accounts/logout/", views.logout_user, name = "logout_user"),
    path("update-profile/", views.update_profile, name = "update_profile"),
    path("profile-picture/upload/", views.profile_pic_upload, name = "profile_pic_upload"),
    path("add-books/", views.add_books, name = "add_books"),
    path("view-books", views.view_books, name = "view_books"),
    path("delete-books-<int:book_id>", views.delete_books, name = "delete_books"),
    path("detail-books-<int:book_id>", views.detail_books, name = "detail_books"),
    path("update-books-<int:book_id>", views.update_books, name = "update_books"),
    path("request-books-<int:book_id>", views.add_book_request, name = "add_book_request"),
    path("change-password/", views.change_password, name = "change_password"),
    path("view-book-user/", views.view_books_user, name = "view_books_user"),
    path("bookrequest-librarian/", views.book_request_librarian, name = "book_request_librarian"),
    path("checkout-book/", views.checkout_book, name = "checkout_book"),
    
    

]

Library Management System/project/project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include('lms.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Library Management System/project/lms/models.py
from django.db import models
from django.contrib.auth.models import User
import datetime

# Create your models here.
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE,related_name="profile")
    is_librarian = models.BooleanField(default=False)
    phone_number = models.CharField(max_length=30, default=" ")
    
    #if there is multiple roles
    # roles = models.ForeignKey(Role, on_delete=models.SET_NULL, null=True) 


    profile_pic = models.ImageField(upload_to="profile_pic", blank=True, null=True) 

    '''blank = True means the field in form can be left emply and
    null= True means the value will be set null if the profile pic left empty'''
    
    created_at = models.DateTimeField(auto_now_add=True)
    '''auto_now_add = True means when the time when the object is added'''

    updated_at = models.DateTimeField(auto_now=True)
    '''auto_now = True means the time when the object is updated'''

    def __str__(self):
        return f"{self.user.username}'s Profile"
    
class Book(models.Model):
    book_name = models.CharField(max_length=50)
    book_author = models.CharField(max_length=50)
    college_class = models.CharField(max_length=50)
    book_stock = models.IntegerField()
    category = models.CharField(max_length=100)
    description = models.TextField(blank=True, null=True)

    def __str__(self):
        return f"{self.book_name} by {self.book_author}"
    
class BookISBN(models.Model):
    book = models.ForeignKey(Book, on_delete=models.CASCADE,related_name="isbn")
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.book.book_name}| ISBN No : {self.id} "
    
class Checkout(models.Model):
    user = models.ForeignKey(User, on_delete=models.DO_NOTHING, null=True, related_name= "checkouts")
    book_isbn = models.ForeignKey(BookISBN, on_delete=models.DO_NOTHING, null= True, related_name="checkouts")
    created_at = models.DateTimeField(auto_now_add=True)
    expiry_date = models.DateTimeField()
    issued_by = models.ForeignKey(User, on_delete=models.DO_NOTHING, null=True, related_name ="checkouts_done")


    def set_expiry_date(self):
        self.expiry_date = self.created_at + datetime.timedelta(days=14)

    def set_issued_by(self,user):
        self.issued_by = user

    def __str__(self):
        return f"{self.book_isbn}-{self.user.username}"
    
    def save(self,*args,**kwargs):
        self.set_expiry_date()
        # self.set_issued_by()

        super(Checkout,self).save(*args, **kwargs)

class BookRequest (models.Model):
    user = models.ForeignKey(User, on_delete= models.DO_NOTHING, related_name= "user")
    book = models.ForeignKey(Book,  on_delete= models.DO_NOTHING, related_name= "book")
    requested_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.user.username} requested {self.book.book_name}"

Library Management System/project/lms/views.py
from django.shortcuts import get_object_or_404, render,redirect
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_http_methods
from django.contrib.auth.models import User
from django.contrib import messages
import re
from django.contrib.auth import authenticate, login, logout
from.import models
from .decorators import has_to_be_librarian, has_to_be_user



@login_required
def dashboard(request):

    return render(request, "lms/dashboard.html")

def home(request):
    return render(request, "lms/home.html")

def login_user(request):
    if request.method == "POST":
        username = request.POST.get("username")
        password = request.POST.get("password")
        user = authenticate(request, username= username, password= password)
        if user is not None:
            login(request, user)
            messages.success(request, "User Loged In Successfully")
            return redirect("lms:dashboard", permanent=True)
        else:
            messages.error(request,"Please enter the valid username or password")
            return redirect("lms:login_user",permanent=True)
    return render(request, "lms/login_page.html")


def signup_user(request):
    if request.method == "POST":
        username = request.POST.get("username")
        password = request.POST.get("password")
        
        
        # Check if username and password length is greater than or equal to 6
        if len(username) < 6 or len(password) < 6:
            messages.error(request, "Username and password must be at least 6 characters long.")
            return redirect("lms:signup_user",permanent=True)
        
        # Password validation
        if not re.search(r'^(?=.*[A-Z])(?=.*[a-z])(?=.*\d)(?=.*[@$!%*?&])[A-Za-z\d@$!%*?&]{6,}$', password):
            messages.error(request, "Password must contain at least one uppercase letter, one lowercase letter, one digit, and one special character (@$!%*?&).")
            return redirect("lms:signup_user",permanent=True)

            # Check if user with the same username
        if User.objects.filter(username=username).exists():
            messages.error(request, f"Person with the username | {username} | already exists.")
            return redirect("lms:signup_user",permanent=True)
        else:
        # Create new user
            user = User.objects.create_user(username=username, email=None, password=password)
            user.save()
            messages.success(request, "User created successfully.")
            return redirect("lms:signup_user", permanent=True)

    return render(request, "lms/signup_user.html")


@login_required
def logout_user(request):
    logout(request)
    messages.success(request, "Logged Out Successfully")
    return redirect("lms:login_user", permanent=True)


@login_required
def update_profile(request):
    if request.method == "POST":
        f_name = request.POST.get("First Name")
        l_name = request.POST.get("Last Name")
        email = request.POST.get("Email")
        phone_number = request.POST.get("Phone Number")
        user = request.user

        if not phone_number.isdigit() or len(phone_number) != 10:
            messages.error(request, "Phone number must be exactly 10 digits and numeric.")
            return redirect("lms:update_profile")
        
        user.first_name = f_name
        user.last_name = l_name
        user.email = email
        user.save()
 
        
        # Check if the profile exists
        if models.Profile.objects.filter(user=user).exists():
            # Profile exists, update it
            profile = models.Profile.objects.get(user=user)
            profile.phone_number = phone_number
            profile.save()
        else:
            # Profile does not exist, create it
            models.Profile.objects.create(user=user, phone_number=phone_number)
        
        return redirect('lms:update_profile')  # or any other success URL

    
    return render(request, "lms/update_profile.html")

@login_required
@has_to_be_librarian
def add_books(request):
    if request.method == "POST":
        book_name = request.POST.get("book_name")
        book_author = request.POST.get("book_author")
        c_class = request.POST.get("c_class")
        book_stock = request.POST.get("stock")
        book_description = request.POST.get("description")
        book_category = request.POST.get("category")
        book =  models.Book.objects.create(book_name=book_name,book_author=book_author,college_class= c_class, book_stock=book_stock,description=book_description,category=book_category)
        for i in range(0,int(book_stock)):
            models.BookISBN.objects.create(book=book)
        messages.success(request, "Books added successfully, auto added ISBNs")
        return redirect("lms:add_books")
    return render(request, "lms/add_books.html")

@login_required
def view_books(request):#for displaying books


    book = models.Book.objects.all()
    context={
        "book":book
    }
    return render(request, "lms/view_books.html",context)
@login_required
def view_books_user(request):#for displaying books


    book = models.Book.objects.all()
    context={
        "book":book
    }
    return render(request, "lms/view_books_user.html",context)

@login_required
@has_to_be_librarian
def delete_books(request, book_id):
    book = models.Book.objects.get(id=book_id)
    book.delete()
    messages.success(request, f"Book : {book} || has been deleted ")
    return redirect("lms:view_books")


@login_required
@has_to_be_librarian
def detail_books(request, book_id):
    book = models.Book.objects.get(id=book_id)
    context = {
        "book":book
    }
    return render(request, "lms/detail_books.html",context)
@login_required
@has_to_be_librarian
def update_books(request, book_id):
    if request.method == "POST":
        book_name = request.POST.get("book_name")
        book_author = request.POST.get("book_author")
        c_class = request.POST.get("c_class")
        book_stock = request.POST.get("stock")
        book_description = request.POST.get("description")
        book_category = request.POST.get("category")

        book = models.Book.objects.get(id=book_id)
        book.book_name = book_name
        book.book_author = book_author
        book.college_class = c_class
        book.book_stock = book_stock
        book.description = book_description
        book.category = book_category
        book.save()
        messages.success(request, f"Book : {book} || has been updated ")
        return redirect ("lms:view_books")
    books = models.Book.objects.get(id=book_id)
    context ={
        "book_name":books.book_name,
        "book_author":books.book_author,
        "book_class":books.college_class,
        "book_stock":books.book_stock,
        "book_description":books.description,
        "book_category":books.category

    }

   
    return render(request, "lms/update_books.html",context)

@require_http_methods(["POST"]) 
@login_required

def profile_pic_upload(request):
    if request.method == "POST":
        profile_pic = request.FILES.get("profile_img")
        if profile_pic:
            try:
                profile = models.Profile.objects.get(user=request.user)
            except models.Profile.DoesNotExist:
                profile = models.Profile.objects.create(user=request.user)
            if profile:
                profile.profile_pic = profile_pic
                profile.save()
                messages.success(request, "Porfile picture updated successfully")
                return redirect("lms:update_profile")
            else:
                messages.error(request, "Profile not found")
                return redirect("lms:update_profile")

        else:
            messages.error(request, "Error updating profile picture")
            return redirect("lms:update_profile")
        
@login_required
def change_password(request):
    if request.method == "POST":
        o_pass = request.POST.get("o_pass")
        n_pass = request.POST.get("n_pass")
        c_pass = request.POST.get("c_pass")
        user = request.user
        if not re.search(r'^(?=.*[A-Z])(?=.*[a-z])(?=.*\d)(?=.*[@$!%*?&])[A-Za-z\d@$!%*?&]{6,}$', n_pass):
            messages.error(request, "Password must contain at least one uppercase letter, one lowercase letter, one digit, and one special character (@$!%*?&).")
            return redirect("lms:update_profile",permanent=True)
        
        if n_pass == c_pass:
            if user.check_password(o_pass):
                user.set_password(n_pass)
                user.save()
                messages.success(request, "Password has been changed successfully")
                return redirect ("lms:update_profile")
            else:
                messages.warning(request, "Your old password is wrong write the correct one")

        else:
                messages.error(request, "New password and confrim password did not match")
    return render (request, "lms/update_profile.html")



@login_required
@has_to_be_user
def add_book_request(request, book_id):
    book = models.Book.objects.get(id=book_id)
    
    # Check if the user has already requested this book
    if models.BookRequest.objects.filter(user=request.user, book=book).exists():
        messages.error(request, "Book Already Requested")
        return redirect("lms:view_books_user")
    
    # Create a new book request
    models.BookRequest.objects.create(user=request.user, book=book)
    messages.success(request, "Book Requested Successfully")
    return redirect("lms:view_books_user")

@login_required
@has_to_be_librarian
def book_request_librarian(request):
    book_request_librarian = models.BookRequest.objects.all()
    context = {"book_req": book_request_librarian
               }
    return render (request, "lms/book_request_librarian.html", context)

@login_required
@has_to_be_librarian
def checkout_book(request):

Library Management System/project/lms/templates/lms/book_request_librarian.html
{% extends "lms/base.html" %}
{% load static %}


{% block inlinecss %}
<link href="{% static 'lms/css/book_request_librarian.css' %}" rel="stylesheet">

{% endblock inlinecss %}
{% block title %}Book Request From User{% endblock title %}
{% block main %}

<body> 


</div>
    <section> 
      {% comment %} <div class="main-content">
        <form action="{% url "lms:search_book" %}" method="GET" class="search-form">
            <input type="text" name="query" placeholder="Search..." class="search-input">
            <input type="submit" value="Search" class="search-button">
        </form>
    </div> {% endcomment %}
      <div class="library-management">
       <h1> List of Book Request  || Library Management System </h1>
    </div>
    <div class="container">
        <div class="tbl-header">
          <table cellpadding="0" cellspacing="0" border="0">
            <thead>
              <tr>
                <th>Request Id</th>
                <th>Book Id</th>
                <th>Book Name</th>
                <th>Requested By</th>
                <th>Book Stock</th>
              </tr>
            </thead>
          </table>
        </div>
        <div class="tbl-content">
          <table cellpadding="0" cellspacing="0" border="0">
            <tbody>
                {% for req in  book_req%}
              <tr>
                <td>{{ req.id }}</td>
                <td>{{ req.book.id }}</td>
                <td>{{ req.book.book_name }} </td>
                {% if req.user.first_name %}
                <td>{{ req.user.first_name }}</td>
                {% else %}
                <td>{{ req.user.username }}</td>
                {% endif %}
                <td>{{ req.book.book_stock }}</td>
         
    
                
               

              {% endfor %}


            </tbody>
            </tbody>
          </table>
        </div>
    </div>

      


<div class="messages">
  {% if messages %}
  {% for messages in  messages%}
  {{messages}}
  {% endfor %}
  {% endif %}
</div>



    </section> 
    <a href="{% url "lms:dashboard" %}" class="yellow-button"><b>--Get Back To Dashboard--</b></a>
    <a href="{% url "lms:checkout_book" %}" class="success-button" style="position: absolute; right: 25%; top: 86%; height: 50px;"><b>--Checkout--</b></a>
</body>
</div>

  

{% endblock main %}

Library Management System/project/lms/templates/lms/checkout_book.html
{% extends "lms/base.html" %}
{% load static %}


{% block inlinecss %}
<link href="{% static 'lms/css/checkout_book.css' %}" rel="stylesheet">

{% endblock inlinecss %}
{% block title %}Checkout Books{% endblock title %}
{% block main %}

<body> 


</div>
    <section> 
      {% comment %} <div class="main-content">
        <form action="{% url "lms:search_book" %}" method="GET" class="search-form">
            <input type="text" name="query" placeholder="Search..." class="search-input">
            <input type="submit" value="Search" class="search-button">
        </form>
    </div> {% endcomment %}
      <div class="library-management">
       <h1> Checkout Books || Library Management System </h1>
    </div>
    <div class="container">
        <div class="tbl-header">
          <table cellpadding="0" cellspacing="0" border="0">
            <thead>
              <tr>
                <th>Checkout Id</th>
                <th>Book ISBN</th>
                <th>Book Name</th>
                <th>Book Author</th>
                <th>User</th>
                <th>Issued Date</th>
                <th>Issued By</th>
                <th>Actions</th>
              </tr>
            </thead>
          </table>
        </div>
        <div class="tbl-content">
          <table cellpadding="0" cellspacing="0" border="0">
            <tbody>
                {% for book in  book%}
              <tr>
                <td>{{ book.id }}</td>
                <td>{{ book.book_name }} </td>
                <td>{{ book.book_author }}</td>
                <td>{{ book.college_class }}</td>
                <td>{{ book.book_stock }}</td>
                <td>{{ book.description }}</td>
                <td>{{ book.category }}</td>
                
                <td>
                    <br>
                    <br>
                    
                    <br>
                    <a href="{% url "lms:detail_books" book.id%}" class="success-button"><b>Details</b></a>


                </td>
                
               
              </tr>

              {% endfor %}


            </tbody>
            </tbody>
          </table>
        </div>
    </div>

      





    </section> 
        <a href="{% url "lms:dashboard" %}" class="yellow-button"><b>--Get Back To Dashboard--</b></a>  
    <a href="" class="success-button" style="position: absolute; right: 25%; top: 86%; height: 50px;"><b>--Checkout--</b></a>



{% endblock main %}

Library Management System/project/lms/templates/lms/dashboard.html
{% extends "lms/base.html" %}
{% load static %}


{% block inlinecss %}
<link href="{% static 'lms/css/dashboard.css' %}" rel="stylesheet">

{% endblock inlinecss %}
{% block title %}Dashboard{% endblock title %}
{% block main %}

<body> 

    <section> 
      <div class="library-management">
       <h1> Dashboard || Library Management System </h1>
    </div>

    <div class="management">
      <h3> Username: {{request.user.username | capfirst}}{% if user.profile.is_librarian %} | Librarian {% else %} | Normal User{% endif %} </h3>
   </div>


    <div class="container">  
        <h1> Update Your Profile</h1>
        <br>
        <p> This button allows you to update your profile in Library Management System, ensuring that your information is kept updated.</p>
        <br>
        
        <a href="{% url "lms:update_profile" %}" class="blue-button"><b>--Update Your Profile--  </b></a>   
    
    </div>
    <div class="container">
      <h1>Add Books | Librarian</h1>
        <br>
        <p> This button allows librarians to add new books to the Library Management System, ensuring the catalog is kept updated.</p>
        <br>
        {% if user.profile.is_librarian %}
        <a href="{% url "lms:add_books" %}" class="yellow-button"><b>--Add Books | Librarian |--  </b></a>   
        {% else %}
        <a class="yellow-button" disabled><b>--Librarian-Only Access--</b></a>

        {% endif %}
    </div>
    <div class="container">
      <h1>Book Control | Librarian</h1>
      <br>
      <p> This button allows librarians to view, update and delete books in LMS, ensuring to Manage Catalog with Updates & Deletions</p>
      <br>
      {% if user.profile.is_librarian %}
      <a href="{% url "lms:view_books" %}" class="green-button"><b>Manage Book | Librarian | </b></a>   
      {% else %}
      <a class="green-button" disabled><b>--Librarian-Only Access--</b></a>

      {% endif %}
    </div>
    
    <div class="container">
      <h1>Book Request | User</h1>
      <br>
      <p> This button allows user to view, and request books in LMS, ensuring a complete and seamless experience for managing book requests. </p>
      <br>
      {% if user.profile.is_librarian %}
      <a class="pink-button" disabled><b>User-Only Access</b></a>

      {% else %}
      <a href="{% url "lms:view_books_user" %}" class="pink-button"><b>Request Book | User | </b></a>   

      {% endif %}
    </div>
    <div class="container">    <h1>Checkout | Librarian</h1>
      <br>
      <p> This button allows the librarian to manage checkouts in the LMS, ensuring a efficient process for tracking and lending books. </p>
      <br>
      {% if user.profile.is_librarian %}
      <a href="{% url "lms:book_request_librarian" %}" class="o_white-button"><b>--Checkout | Librarian |-- </b></a>   


      {% else %}
      <a class="o_white-button" disabled><b>--Librarian-Only Access--</b></a>


      {% endif %}
    </div>
    <div class="container">
        <h1> Logout From System</h1>
        <br>
        <p> This button allows you to securely log out from the Library Management System, ensuring that your session is safely terminated.</p>
        <br>
        
        <a href="{% url "lms:logout_user" %}" class="success-button" onclick="return confirm('Are you sure you want to log out?');">
          <b>--Click Here To Logout--</b>
      </a>
    </div>

    

      <div class="messages">
        {% if messages %}
        {% for messages in  messages%}
        {{messages}}
        {% endfor %}
        {% endif %}
      </div>

    </section> 
  </body>
  

{% endblock main %}

Library Management System/project/lms/templates/lms/detail_books.html
{% extends "lms/base.html" %}
{% load static %}


{% block inlinecss %}
<link href="{% static 'lms/css/detail_books.css' %}" rel="stylesheet">

{% endblock inlinecss %}
{% block title %} Books Detail{% endblock title %}
{% block main %}

<body> 

    <section> 
      <div class="library-management">
       <h1> Delete and Update Books || Library Management System </h1>
    </div>
    <div class="container">
        <div class="tbl-header">
          <table cellpadding="0" cellspacing="0" border="0">
            <thead>
              <tr>
                <th>Book Id</th>
                <th>Book Name</th>
                <th>Book Author</th>
                <th>Class</th>
                <th>Stock</th>
                <th>Description</th>
                <th>Category</th>
                <th>Actions</th>
              </tr>
            </thead>
          </table>
        </div>
        <div class="tbl-content">
          <table cellpadding="0" cellspacing="0" border="0">
            <tbody>
              <tr>
                <td>{{ book.id }}</td>
                <td>{{ book.book_name }} </td>
                <td>{{ book.book_author }}</td>
                <td>{{ book.college_class }}</td>
                <td>{{ book.book_stock }}</td>
                <td>{{ book.description }}</td>
                <td>{{ book.category }}</td>
                
                <td>
                    <br>
                    <br>
                    <form action="{% url 'lms:delete_books' book.id %}" method="post" onsubmit="return confirm('Are you sure you want to delete this book?');">
                      {% csrf_token %}
                      <button type="submit" class="red-button"><b>Delete</b></button>
                  </form>                   
                    <br>
                    <br>
                    <br>
                    
                    <br>
                    <a href="{% url "lms:update_books" book.id%}" class="success-button"><b>Update</b></a>


                </td>
                
               
              </tr>
            </tbody>
            </tbody>
          </table>
        </div>
    </div>

      


<div class="messages">
  {% if messages %}
  {% for messages in  messages%}
  {{messages}}
  {% endfor %}
  {% endif %}
</div>
      <a href="{% url "lms:view_books" %}" class="yellow-button"><b>--Get Back To View Book Page--</b></a>


    </section> 
  </body>
</div>
  

{% endblock main %}

Library Management System/project/lms/templates/lms/update_profile.html
{% extends "lms/base.html" %}
{% load static %}

{% block inlinecss %}
<link href="{% static 'lms/css/update_profile.css' %}" rel="stylesheet">
{% endblock inlinecss %}

{% block title %}{{ request.user.username|capfirst }}'s Profile{% endblock title %}

{% block main %}
<body>
  <div class="messages">
    {% if messages %}
    {% for messages in  messages%}
      {{messages}}
    {% endfor %}
    {% endif %}
    </div> 

    <section> 
        <div class="library-management">
            <h1>{{ request.user.username|capfirst }} || Update Profile</h1>
        </div>
    
            <div class="card h-100">
                <div class="card-body">
                    <div class="account-settings">
                        <div class="user-profile">
                          {% if request.user.profile.profile_pic %}
                          <img   width="310" height="225"src="{{request.user.profile.profile_pic.url}}"alt="userimage">
                          <form action="{% url "lms:profile_pic_upload" %}" method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            <input type="file" name="profile_img"id "profile_img">
                            <button type="submit" class="green-button">--Change--</button>
                            <br>
                          </form>
                          {% else %}
                          
                          <div class="user-avatar">
                            <img width="320" height="200" src="https://bootdey.com/img/Content/avatar/avatar7.png" alt="Maxwell Admin">
                        </div>
                          <form action="{% url "lms:profile_pic_upload" %}" method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            <input type="file" name="profile_img"id "profile_img"><br>
                            
                          
                            <button type="submit" class="green-button">--Upload--</button><br>
                            <br>
                            
                          </form>

                            
                            {% endif %}
                            
                            <br>
                            <h5 class="user-name">{{request.user.first_name|capfirst}} {{request.user.last_name|capfirst}}</h5>
                            <h6 class="user-email">{{request.user.email}}</h6>
                            <h6 class="user-email">{{request.user.profile.phone_number}}</h6>
                            {% if request.user.profile.is_librarian %}
                            <h6 class="user-email">Librarian</h6>
                            {% else %}
                            <h6 class="user-email">Normal User</h6>
                            {% endif %}
                            
                            <br>
                        </div>

                    </div>
                    <a href="{% url "lms:dashboard" %}" class="success-button"><b>--Get Back To Dashboard--</b></a>
                </div>
            </div>
            </div>

            <div class="signin"> 
                <div class="content"> 
                  <h2>Edit Profile</h2> 
                  <form class="form" method="post" action="{% url "lms:update_profile" %}"> 
                    {% csrf_token %}
          
                    <div class="inputBox"> 
                      <input type="text" required name="First Name"> <i>First Name</i> 
                    </div> 

                    <div class="inputBox"> 
                      <input type="text" required name="Last Name"> <i>Last Name</i> 
                    </div> 
          
                    <div class="inputBox"> 
                      <input type="email" required name="Email"> <i>Email</i> 
                    </div> 
                    <div class="inputBox"> 
                      <input type="text" required name="Phone Number"> <i>Phone Number</i> 
                    </div>
                    <div class="inputBox"> 
                      <!-- Inline style to set the button color to black -->
                      <input type="submit" value="Update" > 
                    </div> 
          
                  </form> 
                </div> 
              </div> 
        </div>

            <div class="signin1"> 
                <div class="content1"> 
                  <h2>Change Password</h2> 
                  <form class="form" method="post" action="{% url "lms:change_password" %}">
                    {% csrf_token %}
                    <br>
                    
          
                    <div class="inputBox1"> 
                      <input type="password" required name="o_pass"> <i>Old Password</i> 
                    </div> 
                    <div class="inputBox1"> 
                      <input type="password" required name="n_pass"> <i>New Password</i> 
                    </div> 
                    <div class="inputBox1"> 
                      <input type="password" required name="c_pass"> <i>Confirm Password</i> 
                    </div> 

                    <div class="inputBox1"> 
                      <!-- Inline style to set the button color to black -->
                      <input type="submit" value="Change Password" > 
                      <br>
                      <br>
                      <br>
                      <br>
                      

                    </div> 
          
                  </form> 
                </div> 
              </div> 
        </div>

  
</section> 

{% endblock main %}